"""Real-build verification of the pixi Dockerfile path.

Two guards the string-level generator tests cannot provide:

  * Every pinned base-image digest in ``wfc.environments.dockerfiles.bases`` resolves
    in its registry — a placeholder or stale digest fails every
    pixi/conda build at ``FROM``.
  * The generated pixi Dockerfile actually builds against the real base,
    and the interpreter path recorded in the manifest exists inside the
    built image — the exact path ``wfc run-step`` execs at dispatch time.

Both tests are ``integration``-marked (deselected by default) and skip
cleanly without a reachable Docker daemon. The build test is
additionally ``slow`` — it locks, solves, and downloads a real (minimal)
pixi env.
"""

from __future__ import annotations

import shutil
import subprocess

import pytest

from axiom_annotations import workflow

from tests.conftest import requires_docker


pytestmark = [pytest.mark.integration, requires_docker]


@workflow(
    purpose="Every pinned base-image digest in wfc.environments.dockerfiles.bases "
            "resolves in its registry via `docker manifest inspect` — the "
            "manual bump-the-constant maintainer step is enforced here "
            "instead of trusted (a placeholder digest fails every build "
            "at FROM)."
)
def test_pinned_base_digests_exist_in_registries():
    from wfc.environments.dockerfiles.bases import BASES_BY_BACKEND

    for backend, ref in BASES_BY_BACKEND.items():
        proc = subprocess.run(
            ["docker", "manifest", "inspect", ref],
            capture_output=True,
            text=True,
            timeout=60,
        )
        assert proc.returncode == 0, (
            f"{backend} base {ref!r} does not resolve in its registry: "
            f"{proc.stderr.strip()}"
        )


# Minimal pixi project: python for the interpreter assertion, pip for the
# generator's --no-deps freeze layer (`<env-python> -m pip install`).
# The env is registered under the wfc name "default" because register()
# passes the env name verbatim to `pixi install --environment <name>`,
# and "default" is the one environment every pixi.toml defines.
_SMOKE_PIXI_TOML = """\
[project]
name = "wfc-smoke"
channels = ["conda-forge"]
platforms = ["linux-64"]

[dependencies]
python = "3.12.*"
pip = "*"
"""


@pytest.mark.slow
@workflow(
    purpose="The generated pixi Dockerfile builds end-to-end against the "
            "real pinned base (lock generated by the in-image pixi, "
            "registered through the production wfc.environments.register path with "
            "a real docker build), and the interpreter path recorded in "
            "the manifest exists and runs inside the built image."
)
def test_generated_pixi_dockerfile_builds_and_records_live_interpreter(tmp_path):
    from wfc import environments as envs_mod
    from wfc.environments.dockerfiles.bases import PIXI_BASE
    from wfc.environments.dockerfiles.pixi import env_python_path

    (tmp_path / ".wfc").mkdir()

    # Lock the smoke project with the SAME pixi version the image build
    # will run (`pixi install --locked` rejects a mismatched lock).
    ctx = tmp_path / "ctx"
    ctx.mkdir()
    (ctx / "pixi.toml").write_text(_SMOKE_PIXI_TOML, encoding="utf-8")
    lock_proc = subprocess.run(
        [
            "docker", "run", "--rm",
            "-v", f"{ctx}:/ctx", "-w", "/ctx",
            PIXI_BASE, "pixi", "lock",
        ],
        capture_output=True,
        text=True,
        timeout=600,
    )
    assert lock_proc.returncode == 0, lock_proc.stderr
    lock_text = (ctx / "pixi.lock").read_text(encoding="utf-8")

    # Register through the production path — real docker build, no mocks.
    record = envs_mod.register(
        name="default",
        backend="pixi",
        source={
            "pixi_lock_content": lock_text,
            "pixi_toml_content": _SMOKE_PIXI_TOML,
            "pip_freeze_content": "",
        },
        project_dir=tmp_path,
    )

    # The manifest records the generator's env python, and that exact
    # path runs inside the built image (what run-step will exec).
    assert record.python == env_python_path("default")
    # Run the image by the daemon ref run-step hands Docker (the local
    # env's bare image ID), with pulling forbidden: the run must find the
    # built image on this host's store, classic or containerd.
    from wfc.environments import daemon_ref
    image_ref = daemon_ref(record.container)
    run_proc = subprocess.run(
        ["docker", "run", "--rm", "--pull=never", image_ref,
         record.python, "--version"],
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert run_proc.returncode == 0, run_proc.stderr
    assert "Python 3.12" in (run_proc.stdout + run_proc.stderr), (
        run_proc.stdout, run_proc.stderr,
    )
