/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Serve the main SPA page.
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/contracts/{method_full}/output_columns": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Output Columns
         * @description Resolve declared output columns for a method's slot.
         *
         *     The canvas inspector calls this for params declared with
         *     ``column_of_input: <slot>`` to populate a dropdown of candidate column
         *     names. Reuses ``wfc/contracts.py::resolve_columns`` against the upstream
         *     method's contract.
         *
         *     Args:
         *         method_full: ``module.method`` (e.g. ``data_preprocessing.regionprops``).
         *         slot: Output slot name to resolve columns for.
         *         params: JSON-encoded dict of upstream node's current canvas params
         *             (used by ``from_params`` expansion). Optional; missing/empty
         *             falls back to ``{}``.
         *         run_id: When the upstream is a ``run_reference`` node, pass the
         *             referenced run id; the endpoint then uses Run.params from the
         *             DB as the resolution context.
         *
         *     Returns:
         *         ``{strict, from_params, patterns, all}`` where ``all`` is the
         *         union of resolved column names produced by ``resolve_columns``.
         *         ``patterns`` are returned literally (resolution requires a CSV;
         *         not done here per the no-introspection constraint).
         */
        get: operations["get_output_columns_api_contracts__method_full__output_columns_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/envs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Envs
         * @description Register a container env via :func:`wfc.envs.register`.
         *
         *     Body shape::
         *
         *         {"name": "image-io",
         *          "backend": "pixi" | "conda" | "byo",
         *          "source": {...},                  # per-backend payload
         *          "base_image": "..." | null,       # optional, not valid for byo
         *          "force": false}
         *
         *     Returns the persisted :class:`EnvRecord` as JSON (the manifest record
         *     dict plus a ``name`` key so the caller doesn't have to track it).
         */
        post: operations["post_envs_api_envs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fs/browse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fs Browse
         * @description List directory contents under the project root.
         *
         *     ``path`` is relative to the project root. Defaults to the root itself.
         *     Rejects any path that resolves outside the project root. Safe for a
         *     localhost single-user dev tool: the server is already scoped to the
         *     project the user chose to launch it against.
         */
        get: operations["fs_browse_api_fs_browse_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Modules
         * @description Return modules as a nested dict keyed by module/method name for the builder UI.
         *
         *     Shape: {moduleName: {description, methods: {methodName: {inputs, outputs, ...}}}}
         *     This matches what nodes.js / populateModulePalette() expect.
         */
        get: operations["get_modules_api_modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/pipelines/{pipeline_id}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Document
         * @description Return the literal ``pipeline.json`` written at submission time.
         *
         *     Reads ``<project_root>/.runs/pipelines/<pipeline_id>/pipeline.json`` —
         *     the same file ``WfcProvider._load_bundled_samples`` consumes for fan-in
         *     sample resolution. Returns the parsed JSON document as-is so the
         *     canvas can hand it to ``loadPipeline()`` without transformation.
         *
         *     404 when the file does not exist (the pipeline was authored but
         *     never reached the snake-gen / run-generation stage).
         */
        get: operations["get_pipeline_document_api_pipelines__pipeline_id__document_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Project Status
         * @description Onboarding-shaped project status.
         *
         *     Subset of ENDPOINTS.md §1.1 — reports whether a project is loaded,
         *     its root, and quick counts. Always 200, never 404.
         */
        get: operations["get_project_status_api_project_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/envs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Registry Envs
         * @description List distinct env specs referenced by registered methods.
         *
         *     One row per ``Method.env`` value. Aggregates method names, total run
         *     count, and most-recent run timestamp (``Run.started_at``) across all
         *     methods sharing that env, and resolves the registered env's ``backend``
         *     plus a ``has_packages`` flag (True when a ``source_fingerprint`` was
         *     captured at registration — i.e. a package list is available to attempt).
         *     It does not guarantee a non-empty result: ``GET .../packages`` parses that
         *     blob and may return an empty list if the captured blob carries no
         *     recognizable packages (e.g. an older capture).
         */
        get: operations["get_registry_envs_api_registry_envs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/envs/blob/{md5}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Registry Env Blob
         * @description Read an env-content blob from the DVC content-addressed cache.
         *
         *     Returns the raw blob as ``text/plain`` so the frontend can render it
         *     directly in a code panel. Shares its read path (and path-traversal
         *     guard) with ``GET .../packages`` via :func:`_read_env_blob_text`.
         */
        get: operations["get_registry_env_blob_api_registry_envs_blob__md5__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/envs/{spec}/packages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Registry Env Packages
         * @description Installed-package list for a registered pixi/conda env.
         *
         *     Resolves *spec* to its :class:`wfc.envs.EnvRecord`, reads the captured
         *     ``source_fingerprint`` blob from the DVC cache, and parses it into a
         *     sorted, de-duplicated, source-tagged package list via
         *     :func:`wfc.env_packages.parse_packages`.
         *
         *     Honest empty state: a byo env, an env that never staged source content,
         *     or an unmatched spec returns ``captured: false`` with ``packages: []`` —
         *     never a fabricated list.
         *
         *     Response::
         *
         *         {"spec": "container:demo",
         *          "backend": "pixi" | "conda" | "byo" | null,
         *          "captured": true,
         *          "packages": [{"name": ..., "version": ..., "source": "pixi"}, ...]}
         */
        get: operations["get_registry_env_packages_api_registry_envs__spec__packages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Registry Methods
         * @description List registered methods for the Registry tab.
         *
         *     Shape (subset of ENDPOINTS.md §2.2): `{methods: [{name, module, env,
         *     validated, runCount, source}]}`.
         *
         *     `validated` replaces the handoff's `status: "ok"|"stale"|"broken"` with
         *     a `bool | null` sourced from the dryRun cache (null = never checked).
         */
        get: operations["get_registry_methods_api_registry_methods_get"];
        put?: never;
        /**
         * Register Method Endpoint
         * @description Wrap ``wfc.register.register_method`` with optional dry-run preflight.
         */
        post: operations["register_method_endpoint_api_registry_methods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/methods/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Registry Method
         * @description Re-validate an existing method's env+import. Caches by fingerprint.
         */
        post: operations["validate_registry_method_api_registry_methods_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/methods/{module_name}/{method_name}/detail": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Registry Method Detail
         * @description Read-only view of a method's directory + its parsed contract.
         *
         *     Lists every file in the method dir (no recursion) with its content and a
         *     language hint for syntax highlighting. Returns the DB-parsed contract
         *     (input_slots, output_slots, params_schema) alongside so the frontend can
         *     render it as structured tables without re-parsing YAML.
         */
        get: operations["get_registry_method_detail_api_registry_methods__module_name___method_name__detail_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Registry Modules
         * @description List registered modules for the Registry tab.
         *
         *     Shape matches design_handoff_onboarding/ENDPOINTS.md §2.1 (subset):
         *     `{modules: [{name, description, contracts[], methods, source}]}`.
         *     `color` is intentionally omitted -- the frontend assigns it from the
         *     `MOD_COLORS` cycle by registration order.
         */
        get: operations["get_registry_modules_api_registry_modules_get"];
        put?: never;
        /**
         * Register Module Endpoint
         * @description Wrap ``wfc.register.register_module`` with optional dry-run preflight.
         */
        post: operations["register_module_endpoint_api_registry_modules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/registry/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Registry Samples
         * @description List registered samples for the Registry tab.
         *
         *     Shape (subset of ENDPOINTS.md §2.4): `{samples: [{name, source, size,
         *     hash, pushed, runCount, registered_at}]}`.
         *
         *     `pushed` is `True` when a DVC content hash is present (indicates the sample
         *     is in the DVC cache and pushable to the remote); `False` otherwise.
         */
        get: operations["get_registry_samples_api_registry_samples_get"];
        put?: never;
        /**
         * Register Sample Endpoint
         * @description Wrap ``wfc.cli.register_sample`` behind an HTTP endpoint.
         */
        post: operations["register_sample_endpoint_api_registry_samples_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}/lineage-pipeline": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Run Lineage Pipeline
         * @description Return a synthesized literal-only lineage pipeline for ``run_id``.
         *
         *     Walks ``parentRunIds`` from the clicked run back to roots — through
         *     pipeline boundaries — and synthesizes a flat literal-only pipeline
         *     JSON suitable for the canvas's ``loadPipeline()``. See
         *     ``wfc.canvas.lineage_synthesizer`` for the algorithm.
         *
         *     Status codes:
         *       - 200 with synthesized JSON on success
         *       - 404 if the run id is unknown
         *       - 422 if synthesis fails (cycle defense, malformed ancestor chain)
         */
        get: operations["get_run_lineage_pipeline_api_runs__run_id__lineage_pipeline_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/completed-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wfc Completed Runs
         * @description Return completed runs with output slots for Run Reference nodes.
         */
        get: operations["get_wfc_completed_runs_api_wfc_completed_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/experiments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfc Experiments */
        get: operations["get_wfc_experiments_api_wfc_experiments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/export-artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Wfc Artifacts
         * @description Zip download of wfc run artifacts, optionally filtered by file type.
         */
        post: operations["export_wfc_artifacts_api_wfc_export_artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/export-csvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Export Wfc Csvs
         * @description Zip download of CSV artifacts from wfc runs.
         */
        post: operations["export_wfc_csvs_api_wfc_export_csvs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/lineage/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfc Lineage */
        get: operations["get_wfc_lineage_api_wfc_lineage__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/load": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Load Wfc Data
         * @description Load (or reload) the wfc provider from a project path.
         *
         *     Also updates DATABASE_URL and resets the SQLAlchemy engine so that
         *     GET /api/modules queries this project's DB, not the server's launch-cwd DB.
         */
        post: operations["load_wfc_data_api_wfc_load_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/methods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfc Methods */
        get: operations["get_wfc_methods_api_wfc_methods_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfc Modules */
        get: operations["get_wfc_modules_api_wfc_modules_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/preview-artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Wfc Artifacts
         * @description Preview what would be exported (all file types) without downloading.
         */
        post: operations["preview_wfc_artifacts_api_wfc_preview_artifacts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/preview-csvs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Preview Wfc Csvs
         * @description Preview CSV export (counts + sizes) without downloading.
         */
        post: operations["preview_wfc_csvs_api_wfc_preview_csvs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Wfc Data
         * @description Reload wfc data from the current project root.
         */
        post: operations["refresh_wfc_data_api_wfc_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/run/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfc Run */
        get: operations["get_wfc_run_api_wfc_run__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Wfc Run
         * @description Partial-update a run's user-editable metadata.
         */
        patch: operations["patch_wfc_run_api_wfc_run__run_id__patch"];
        trace?: never;
    };
    "/api/wfc/run/{run_id}/artifact/{artifact_path}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfc Artifact */
        get: operations["get_wfc_artifact_api_wfc_run__run_id__artifact__artifact_path__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/run/{run_id}/artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Wfc Artifacts */
        get: operations["list_wfc_artifacts_api_wfc_run__run_id__artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/run/{run_id}/cancelled-descendants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wfc Cancelled Descendants
         * @description Return runs cancelled because ``run_id`` (or its subtree) failed.
         */
        get: operations["get_wfc_cancelled_descendants_api_wfc_run__run_id__cancelled_descendants_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/run/{run_id}/stream-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Run Logs
         * @description Stream a run's stdout/stderr as SSE events, ending with a `terminal` event.
         *
         *     - Terminal runs (status in {completed, success, failed, cancelled}):
         *       read the on-disk log files, emit each line as a `stdout`/`stderr`
         *       event, then emit the `terminal` event and close. ``?full=1`` returns
         *       the whole file; default tails the last ``tail`` lines (default 500).
         *     - Running runs: poll the log files every ~200 ms, emit new lines as they
         *       appear, stop when the DB status transitions off ``running`` and emit a
         *       final `terminal` event.
         */
        get: operations["stream_run_logs_api_wfc_run__run_id__stream_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfc Runs */
        get: operations["get_wfc_runs_api_wfc_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/samples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Wfc Samples
         * @description Return detailed info for all registered samples.
         */
        get: operations["get_wfc_samples_api_wfc_samples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfc Status */
        get: operations["get_wfc_status_api_wfc_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/wfc/tree/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Wfc Run Tree */
        get: operations["get_wfc_run_tree_api_wfc_tree__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/cancel/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Workflow
         * @description Cancel an in-flight pipeline (ADR-015 Phase D Pass 2).
         *
         *     Terminates the live Snakemake subprocess (and its descendants) and
         *     flips any ``running`` rows for this pipeline to ``cancelled`` with
         *     ``error_message="Cancelled by user"``.  Idempotent: cancelling a
         *     pipeline whose process has already exited returns 200 with a no-op
         *     indication.  Returns 404 for unknown job_ids.
         */
        post: operations["cancel_workflow_api_workflow_cancel__job_id__post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Workflow
         * @description Submit a pipeline for execution via Snakemake.
         *
         *     Enriches the PipelineJSON with script paths and slot_outputs from the DB,
         *     writes it to a temp file, and spawns a background thread running
         *     ``run_pipeline()``. Returns the pipeline_id as the job_id immediately.
         *
         *     Rejects empty pipelines with HTTP 400.  Before spawning the run thread it
         *     pre-flights Docker and git (cycle decision D-6, 3-lite): a not-ready
         *     environment is rejected with HTTP 409 carrying a kind-tagged
         *     ``{kind, message, hint}`` payload (the same shape the frontend renders for
         *     pre-run errors), so no orphan run is started.  Multiple pipelines may run
         *     concurrently — each gets its own pipeline_id-scoped workspace.
         */
        post: operations["run_workflow_api_workflow_run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/save": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Save Workflow
         * @description Save a workflow definition.
         *
         *     Note: ``Workflow`` was previously declared as the pydantic class for
         *     this body, but the symbol was never defined in this module — this
         *     endpoint has been a runtime no-op behind that broken reference.  The
         *     untyped ``Dict[str, Any]`` keeps the endpoint reachable and lets
         *     FastAPI's OpenAPI generation succeed, which in turn unblocks the
         *     ADR-015 Phase D codegen pipeline.  Callers should treat the body as
         *     free-form JSON until/unless this endpoint is properly typed.
         */
        post: operations["save_workflow_api_workflow_save_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/status/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Workflow Status
         * @description Return per-step and overall status for a running or completed pipeline.
         *
         *     Queries the ``runs`` table by ``pipeline_id`` and derives overall status.
         *     Also returns whether the background thread is still alive and any captured
         *     log output.
         *
         *     Args:
         *         job_id: The pipeline_id returned by the run endpoint.
         *
         *     Returns:
         *         JSON with ``job_id``, ``overall_status``, ``steps``, ``thread_alive``,
         *         ``log``, and ``error`` fields.
         */
        get: operations["get_workflow_status_api_workflow_status__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Workflow
         * @description Validate a pipeline graph against registered methods in the DB.
         */
        post: operations["validate_workflow_api_workflow_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/workflow/{pipeline_id}/editable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Pipeline Editable
         * @description Return the pre-substitution pipeline JSON (with variables + {$var}).
         *
         *     Falls back to ``pipeline.json`` (post-substitution) for legacy runs that
         *     were submitted before the editable sidecar existed.
         */
        get: operations["get_pipeline_editable_api_workflow__pipeline_id__editable_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ContractSpec */
        ContractSpec: {
            /** Name */
            name: string;
            /**
             * Required
             * @default true
             */
            required: boolean;
            /** Type */
            type: string;
            /** Value Type */
            value_type?: string | null;
        };
        /** ExportArtifactsRequest */
        ExportArtifactsRequest: {
            /** File Types */
            file_types?: string[] | null;
            /** Run Ids */
            run_ids?: string[] | null;
        };
        /** ExportCSVsRequest */
        ExportCSVsRequest: {
            /** Run Ids */
            run_ids?: string[] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MethodRegisterRequest */
        MethodRegisterRequest: {
            /** Directory */
            directory: string;
            /** Method Name */
            method_name?: string | null;
            /** Module */
            module: string;
        };
        /** MethodValidateRequest */
        MethodValidateRequest: {
            /** Method */
            method: string;
            /** Module */
            module: string;
        };
        /** ModuleRegisterRequest */
        ModuleRegisterRequest: {
            /**
             * Contracts
             * @default []
             */
            contracts: components["schemas"]["ContractSpec"][];
            /** Description */
            description?: string | null;
            /** Folder */
            folder?: string | null;
            /** Name */
            name: string;
        };
        /** NodeRunState */
        NodeRunState: {
            /** Cache Hit */
            cache_hit?: boolean | null;
            /** Cache Key */
            cache_key?: string | null;
            /** Cancelled Due To Run Id */
            cancelled_due_to_run_id?: string | null;
            /** Error */
            error?: string | null;
            /** Error Run Id */
            error_run_id?: string | null;
            /** Error Sample */
            error_sample?: string | null;
            /** Original Run Id */
            original_run_id?: string | null;
            /**
             * Push Failed Count
             * @default 0
             */
            push_failed_count: number;
            /**
             * Push Pending Count
             * @default 0
             */
            push_pending_count: number;
            /**
             * Push State
             * @default deferred
             */
            push_state: string;
            /** Run Ids */
            run_ids?: string[] | null;
            /** Status */
            status: string;
            /** Tally */
            tally?: {
                [key: string]: number;
            } | null;
            /** Upstream Node Id */
            upstream_node_id?: string | null;
            /** Upstream Run Id */
            upstream_run_id?: string | null;
        };
        /** PipelineInput */
        PipelineInput: {
            /** Explicit Combos */
            explicit_combos?: {
                [key: string]: unknown;
            }[] | null;
            /**
             * Keep Going
             * @default false
             */
            keep_going: boolean;
            /**
             * Links
             * @default []
             */
            links: components["schemas"]["PipelineLink"][];
            /** Name */
            name?: string | null;
            /** Nodes */
            nodes: components["schemas"]["PipelineNode"][];
            /** Param Sets */
            param_sets?: {
                [key: string]: {
                    [key: string]: {
                        [key: string]: unknown;
                    };
                };
            } | null;
            /**
             * Samples
             * @default []
             */
            samples: string[];
            /** Variables */
            variables?: {
                [key: string]: unknown;
            } | null;
        };
        /** PipelineLink */
        PipelineLink: {
            /** Source */
            source: string;
            /** Sourcehandle */
            sourceHandle?: string | null;
            /** Target */
            target: string;
            /** Targethandle */
            targetHandle?: string | null;
        };
        /** PipelineNode */
        PipelineNode: {
            /** Fan Mode */
            fan_mode?: string | null;
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /**
             * Method
             * @default
             */
            method: string;
            /** Module */
            module?: string | null;
            /** Output Slot */
            output_slot?: string | null;
            /**
             * Params
             * @default {}
             */
            params: {
                [key: string]: unknown;
            };
            /** Position */
            position?: {
                [key: string]: number;
            } | null;
            /** Run Id */
            run_id?: string | null;
            /** Samples */
            samples?: string[] | null;
            /** Source */
            source?: string | null;
            /**
             * Type
             * @default method
             */
            type: string | null;
        };
        /**
         * RegisterEnvRequest
         * @description Body for ``POST /api/envs``. See :func:`wfc.envs.register`.
         *
         *     No ``push`` field — ADR-019's 2026-05-17 amendment defers
         *     registry push to v1.x. The canvas surface mirrors the CLI flags.
         */
        RegisterEnvRequest: {
            /** Backend */
            backend: string;
            /** Base Image */
            base_image?: string | null;
            /**
             * Force
             * @default false
             */
            force: boolean;
            /** Name */
            name: string;
            /**
             * Source
             * @default {}
             */
            source: {
                [key: string]: unknown;
            };
        };
        /**
         * RunPatchRequest
         * @description Partial update for a Run's user-editable metadata.
         *
         *     All fields are optional; missing fields are left unchanged. `nid`
         *     writes through to `Run.nid` (provenance table); the rest upsert a
         *     `RunAnnotation` row.
         *
         *     `archived` is a bool at the API boundary and maps to the nullable
         *     `archived_at` timestamp column: ``true`` sets it to now, ``false``
         *     clears it.
         */
        RunPatchRequest: {
            /** Archived */
            archived?: boolean | null;
            /** Favorite */
            favorite?: boolean | null;
            /** Nid */
            nid?: string | null;
            /** Tags */
            tags?: string[] | null;
        };
        /** SampleRegisterRequest */
        SampleRegisterRequest: {
            /** Name */
            name: string;
            /**
             * Registration Mode
             * @default copy
             */
            registration_mode: string | null;
            /** Source */
            source: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WfcConfig */
        WfcConfig: {
            /** Project Root */
            project_root: string;
        };
        /** WorkflowStatusResponse */
        WorkflowStatusResponse: {
            /** Error */
            error?: unknown | null;
            /** Job Id */
            job_id: string;
            /** Log */
            log: string;
            /** Node States */
            node_states: {
                [key: string]: components["schemas"]["NodeRunState"];
            };
            /** Overall Status */
            overall_status: string;
            /** Steps */
            steps: {
                [key: string]: string;
            };
            /** Thread Alive */
            thread_alive: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_output_columns_api_contracts__method_full__output_columns_get: {
        parameters: {
            query: {
                slot: string;
                params?: string | null;
                run_id?: string | null;
            };
            header?: never;
            path: {
                method_full: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_envs_api_envs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterEnvRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    fs_browse_api_fs_browse_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_modules_api_modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_pipeline_document_api_pipelines__pipeline_id__document_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_status_api_project_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_registry_envs_api_registry_envs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_registry_env_blob_api_registry_envs_blob__md5__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                md5: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_registry_env_packages_api_registry_envs__spec__packages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                spec: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_registry_methods_api_registry_methods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_method_endpoint_api_registry_methods_post: {
        parameters: {
            query?: {
                dryRun?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MethodRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_registry_method_api_registry_methods_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MethodValidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_registry_method_detail_api_registry_methods__module_name___method_name__detail_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                module_name: string;
                method_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_registry_modules_api_registry_modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_module_endpoint_api_registry_modules_post: {
        parameters: {
            query?: {
                dryRun?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModuleRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_registry_samples_api_registry_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_sample_endpoint_api_registry_samples_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SampleRegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_lineage_pipeline_api_runs__run_id__lineage_pipeline_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wfc_completed_runs_api_wfc_completed_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_wfc_experiments_api_wfc_experiments_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    export_wfc_artifacts_api_wfc_export_artifacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportArtifactsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_wfc_csvs_api_wfc_export_csvs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCSVsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wfc_lineage_api_wfc_lineage__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    load_wfc_data_api_wfc_load_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WfcConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wfc_methods_api_wfc_methods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_wfc_modules_api_wfc_modules_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    preview_wfc_artifacts_api_wfc_preview_artifacts_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportArtifactsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_wfc_csvs_api_wfc_preview_csvs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExportCSVsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_wfc_data_api_wfc_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_wfc_run_api_wfc_run__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_wfc_run_api_wfc_run__run_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wfc_artifact_api_wfc_run__run_id__artifact__artifact_path__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
                artifact_path: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_wfc_artifacts_api_wfc_run__run_id__artifacts_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wfc_cancelled_descendants_api_wfc_run__run_id__cancelled_descendants_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_run_logs_api_wfc_run__run_id__stream_logs_get: {
        parameters: {
            query?: {
                full?: number;
                tail?: number;
            };
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_wfc_runs_api_wfc_runs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_wfc_samples_api_wfc_samples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_wfc_status_api_wfc_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_wfc_run_tree_api_wfc_tree__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_workflow_api_workflow_cancel__job_id__post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_workflow_api_workflow_run_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_workflow_api_workflow_save_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workflow_status_api_workflow_status__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkflowStatusResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_workflow_api_workflow_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PipelineInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_pipeline_editable_api_workflow__pipeline_id__editable_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pipeline_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
