"""
Project initializer — scaffold a new wfc project directory.

Creates the `.wfc/` config directory, `modules/` and `methods/` directories,
`.runs/` artifact store, `.gitignore`, and initializes the SQLite database
with the full schema.

Usage:
    from wfc.init import init_project

    init_project(Path("."))          # scaffold current directory
    init_project(Path("my_project"))  # scaffold a specific directory
"""

from __future__ import annotations

import os
import re
import subprocess
import textwrap
from pathlib import Path

from axiom_annotations import workflow, task, Step

# Default config template (TOML)
_DEFAULT_CONFIG = textwrap.dedent("""\
    # wfc project configuration
    # Generated by `wfc init`

    [database]
    url = "sqlite:///{db_path}"

    [project]
    name = "{project_name}"

    # Pixi environment root directory.
    # Environments are discovered by globbing <pixi_root>/<env_name>-*/envs/default/
    # Set to an absolute path to use a shared env store across projects.
    [pixi]
    root = ".pixi"

    # DVC provenance storage (ADR-007, ADR-018).
    # `url` is the artifact archive location (any DVC-supported scheme).
    # The default is a durable per-project directory outside this repo;
    # blobs there are indexed by `.wfc/wfc.db`, so back up `.wfc/` to keep
    # provenance recoverable (the archive itself is not tracked in git).
    [dvc]
    url = "{dvc_url}"
    auto_init = true
""")

# Lines to add to .gitignore (only if not already present)
_GITIGNORE_LINES = [
    ".wfc/wfc.db",
    ".wfc/cache/",
    ".runs/",
    "data/",
    "__pycache__/",
]


_GITHUB_SSH_RE = re.compile(
    r"^git@github\.com[:/](?P<owner>[^/]+)/(?P<repo>[^/]+?)(?:\.git)?/?$"
)
_GITHUB_HTTPS_RE = re.compile(
    r"^https?://github\.com/(?P<owner>[^/]+)/(?P<repo>[^/]+?)(?:\.git)?/?$"
)


def _derive_registry_default(origin_url: str | None) -> str:
    """Derive the default registry URL from a git origin URL.

    Returns ``"ghcr.io/<owner>"`` when *origin_url* matches a github.com
    SSH (``git@github.com:owner/repo``) or HTTPS
    (``https://github.com/owner/repo``) shape. Returns the empty string
    when *origin_url* is ``None``, empty, or does not match a github
    shape — the prompt then shows no default.

    Args:
        origin_url: The output of ``git remote get-url origin``, or
            ``None`` when no origin is configured.

    Returns:
        ``"ghcr.io/<owner>"`` for github origins, else ``""``.
    """
    if not origin_url:
        return ""
    m = _GITHUB_SSH_RE.match(origin_url.strip()) or _GITHUB_HTTPS_RE.match(
        origin_url.strip()
    )
    if not m:
        return ""
    return f"ghcr.io/{m.group('owner')}"


def _is_git_repo(directory: Path) -> bool:
    """Return True if *directory* is inside a git working tree."""
    result = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        cwd=str(directory),
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def _initial_commit(project_dir: Path) -> None:
    """Stage tracked project files and create the first git commit.

    Only adds .gitignore and .wfc/wf-canvas.toml — never the database file.
    Uses inline git identity so no global git config is required.
    """
    to_stage = [".gitignore", ".wfc/wf-canvas.toml"]
    for rel in to_stage:
        p = project_dir / rel
        if p.exists():
            subprocess.run(
                ["git", "add", rel],
                cwd=str(project_dir), check=True,
            )

    result = subprocess.run(
        [
            "git",
            "-c", "user.email=wfc@wfc",
            "-c", "user.name=wfc",
            "commit",
            "-m", "wfc init",
        ],
        cwd=str(project_dir),
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise RuntimeError(f"Initial git commit failed: {result.stderr.strip()}")


def _has_head_commit(directory: Path) -> bool:
    """Return True if the repo at *directory* has at least one commit (HEAD)."""
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(directory), capture_output=True, text=True,
    )
    return result.returncode == 0


def _has_global_git_identity() -> bool:
    """Return True if both global user.name and user.email are configured."""
    name = subprocess.run(
        ["git", "config", "--global", "user.name"],
        capture_output=True, text=True,
    )
    email = subprocess.run(
        ["git", "config", "--global", "user.email"],
        capture_output=True, text=True,
    )
    return bool(name.stdout.strip()) and bool(email.stdout.strip())


def _default_archive_url(project_dir: Path) -> str:
    """Return the default DVC archive URL for a project.

    The default is a durable per-project directory under the user's home —
    ``~/.wfc/archives/<project>`` — expressed as an absolute ``file://`` URL
    so it lives outside the project repo and survives across re-clones.

    Args:
        project_dir: The project root (its name is used as the archive
            subdirectory name).

    Returns:
        A ``file://<absolute-path>`` URL string.
    """
    archive_dir = (Path.home() / ".wfc" / "archives" / project_dir.name).resolve()
    return f"file://{archive_dir.as_posix()}"


def _resolve_archive_url(
    project_dir: Path,
    archive: str | None = None,
    assume_yes: bool = False,
) -> str:
    """Resolve the DVC archive location for a fresh ``wfc init``.

    Resolution order:
      1. An explicit ``archive`` value (from ``--archive PATH``) — used as-is
         (a bare path is normalized to a ``file://`` URL).
      2. Otherwise, in non-interactive mode (``assume_yes``) or when stdin is
         not a TTY, the default.
      3. Otherwise, an interactive prompt that leads with what the archive is
         and lets the user press Enter to accept the default.

    Args:
        project_dir: The project root.
        archive: Explicit archive location, or ``None`` to use the default /
            prompt.
        assume_yes: When ``True``, skip the prompt and use the default.

    Returns:
        A DVC archive URL string.
    """
    default = _default_archive_url(project_dir)

    if archive:
        return _normalize_archive(archive, project_dir)

    if assume_yes or not _stdin_is_interactive():
        return default

    print(
        "\nDVC archive (provenance storage)\n"
        "  wfc stores every run's outputs here, content-addressed and indexed\n"
        "  by .wfc/wfc.db. The default is a durable folder outside this repo.\n"
    )
    try:
        answer = input(f"  Archive location [{default}]: ").strip()
    except EOFError:
        answer = ""
    if not answer:
        return default
    return _normalize_archive(answer, project_dir)


def _normalize_archive(value: str, project_dir: Path) -> str:
    """Normalize a user-supplied archive location to a DVC URL.

    A value that already carries a scheme (``file://``, ``s3://``, ``ssh://``,
    ...) is returned unchanged.  A bare filesystem path is expanded
    (``~``), resolved to an absolute path relative to *project_dir* when
    needed, and prefixed with ``file://``.

    Args:
        value: The user-supplied archive location.
        project_dir: The project root (for resolving relative paths).

    Returns:
        A DVC archive URL string.
    """
    value = value.strip()
    if "://" in value:
        return value
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = (project_dir / path).resolve()
    else:
        path = path.resolve()
    return f"file://{path.as_posix()}"


def _stdin_is_interactive() -> bool:
    """Return True if stdin is an interactive TTY (safe to prompt)."""
    import sys
    try:
        return sys.stdin is not None and sys.stdin.isatty()
    except (ValueError, AttributeError):
        return False


@workflow(purpose="Scaffold a new wfc project directory with database, config, and artifact store")
def init_project(
    project_dir: Path,
    init_git: bool = False,
    archive: str | None = None,
    assume_yes: bool = False,
) -> dict[str, bool]:
    """Scaffold a wfc project directory and wire it up to be runnable.

    Creates the directory structure and config files needed for a new wfc
    project, then attempts to bring the project to a runnable state: a live
    DVC archive, a git repo with a clean HEAD, and a Docker pre-flight check.
    Safe to run in a non-empty directory — existing files are never
    overwritten, and re-running fills only previously-missing pieces
    (idempotent).

    git and Docker are hard run-requirements that init detects and surfaces
    but never installs.  A missing/failing git or Docker does NOT abort init:
    the scaffold still completes, the gap is shown loudly in the closing
    health summary, and init still exits 0 (cycle decision D-3/D-4).

    Args:
        project_dir: Root directory for the project (created if needed).
        init_git: Accepted no-op alias — git is now initialized by default.
            Retained for backward compatibility with scripts/docs.
        archive: Explicit DVC archive location (any DVC URL or path).  When
            provided, the wizard does not prompt for it.  Defaults to
            ``file://~/.wfc/archives/<project>`` (expanded to an absolute
            path outside the repo).
        assume_yes: When ``True``, run fully non-interactively (accept all
            defaults, never call ``input()``).  Set by ``wfc init --yes``.

    Returns:
        Dict mapping each created resource name to ``True`` if created
        or ``False`` if already existed.

    The created structure::

        project_dir/
          .wfc/
            wf-canvas.toml   ← SQLite connection string
            wfc.db         ← empty database with schema
          modules/        ← nested module/method hierarchies
          methods/        ← flat standalone method scripts
          .runs/          ← artifact archive store
          .gitignore      ← ignore DB and .runs/
    """
    project_dir = Path(project_dir).resolve()
    created: dict[str, bool] = {}

    # One-time legacy .pm/ -> .wfc/ migration (ADR-021). No-op for fresh
    # projects and for projects already on .wfc/.
    from .database import migrate_legacy_state_dir
    migrate_legacy_state_dir(project_dir)

    口 = Step(step_num=1, name="Create project directories",
             purpose="Make .wfc/, modules/, methods/, and .runs/ directories without overwriting existing content")

    # .wfc/ config directory
    wfc_dir = project_dir / ".wfc"
    created[".wfc/"] = not wfc_dir.exists()
    wfc_dir.mkdir(parents=True, exist_ok=True)

    # modules/ directory — nested module/method hierarchies
    modules_dir = project_dir / "modules"
    created["modules/"] = not modules_dir.exists()
    modules_dir.mkdir(exist_ok=True)

    # methods/ directory — flat standalone methods
    methods_dir = project_dir / "methods"
    created["methods/"] = not methods_dir.exists()
    methods_dir.mkdir(exist_ok=True)

    # data/samples/ — registered sample data store
    data_dir = project_dir / "data" / "samples"
    created["data/samples/"] = not data_dir.exists()
    data_dir.mkdir(parents=True, exist_ok=True)

    # .runs/ artifact store
    runs_dir = project_dir / ".runs"
    created[".runs/"] = not runs_dir.exists()
    runs_dir.mkdir(exist_ok=True)

    口 = Step(step_num=2, name="Write config file",
             purpose="Generate wf-canvas.toml with SQLite database path and a live "
                     "[dvc] archive location if it does not already exist")

    config_path = wfc_dir / "wf-canvas.toml"
    if not config_path.exists():
        db_path = (wfc_dir / "wfc.db").as_posix()
        project_name = project_dir.name
        # Resolve the DVC archive location: explicit --archive, else the
        # interactive wizard prompt (Enter-past default), else the default.
        dvc_url = _resolve_archive_url(
            project_dir, archive=archive, assume_yes=assume_yes
        )
        config_path.write_text(
            _DEFAULT_CONFIG.format(
                db_path=db_path,
                project_name=project_name,
                dvc_url=dvc_url,
            ),
            encoding="utf-8",
        )
        created["wf-canvas.toml"] = True
    else:
        # Idempotent: an existing config is reused verbatim — never
        # re-prompted, never clobbered.
        created["wf-canvas.toml"] = False

    口 = Step(step_num=3, name="Initialize database",
             purpose="Create the SQLite database and apply the full schema via SQLModel")

    db_path = wfc_dir / "wfc.db"
    created["wfc.db"] = not db_path.exists()

    # Set DATABASE_URL so get_engine() picks up the right path
    db_url = f"sqlite:///{db_path}"
    old_url = os.environ.get("DATABASE_URL")
    os.environ["DATABASE_URL"] = db_url

    try:
        from .database import reset_engine, get_engine
        reset_engine()
        get_engine()  # triggers SQLModel.metadata.create_all()
    finally:
        # Restore previous DATABASE_URL (important for tests)
        if old_url is not None:
            os.environ["DATABASE_URL"] = old_url
        else:
            os.environ.pop("DATABASE_URL", None)
        reset_engine()

    口 = Step(step_num=4, name="Update .gitignore",
             purpose="Append wfc-specific ignore rules without overwriting existing entries")

    gitignore_path = project_dir / ".gitignore"
    if gitignore_path.exists():
        existing = gitignore_path.read_text()
    else:
        existing = ""
        created[".gitignore"] = True

    lines_to_add = [line for line in _GITIGNORE_LINES if line not in existing]
    if lines_to_add:
        # Add a blank line separator if file is non-empty and doesn't end with newline
        separator = "\n" if existing and not existing.endswith("\n") else ""
        gitignore_path.write_text(existing + separator + "\n".join(lines_to_add) + "\n")
        if ".gitignore" not in created:
            created[".gitignore"] = True  # modified existing
    else:
        if ".gitignore" not in created:
            created[".gitignore"] = False  # nothing new added

    口 = Step(step_num=5, name="Initialize git repository",
             purpose="git is a hard run-requirement: always attempt git init + an "
                     "initial commit; continue-on-fail (never abort init) — a "
                     "missing binary or failed commit is surfaced in the health "
                     "summary, not raised (D-3)")

    # git default-on, continue-on-fail (symmetric with Docker, D-3). A
    # missing git binary or a failed commit must NOT abort the scaffold — it
    # is caught and downgraded to a health-summary FAIL.
    created[".git/"] = False
    try:
        in_repo = _is_git_repo(project_dir)
        if not in_repo:
            init_res = subprocess.run(
                ["git", "init", str(project_dir)],
                capture_output=True, text=True,
            )
            if init_res.returncode != 0:
                raise RuntimeError(init_res.stderr.strip() or "git init failed")
            created[".git/"] = True
            print("  + Initialized git repository.")
            # Initial commit — stages config and ignore file only (not the DB).
            # Uses an inline fallback identity so no global git config is
            # required; print a note that it can be overridden via `git config`.
            _initial_commit(project_dir)
            if not _has_global_git_identity():
                print(
                    "    (committed with a fallback identity 'wfc <wfc@wfc>';\n"
                    "     set your own with `git config user.name/user.email`)"
                )
        else:
            # Existing repo: only commit if there is no HEAD yet AND the
            # tracked config/ignore files are not already committed. A clean
            # HEAD is left untouched (idempotent — no re-commit).
            if not _has_head_commit(project_dir):
                _initial_commit(project_dir)
                print("  + Created initial git commit.")
    except FileNotFoundError:
        # git binary missing entirely.
        print("\n  WARNING: git is not installed — see the health summary below.")
    except Exception as exc:  # noqa: BLE001 — continue-on-fail by design
        print(f"\n  WARNING: git setup did not complete: {exc}")

    口 = Step(step_num=6, name="Initialize DVC provenance",
             purpose="Auto-init DVC when [dvc] section is present in wf-canvas.toml (ADR-007)")

    # Read config to check for [dvc] section
    try:
        config = read_config(project_dir)
        dvc_config = config.get("dvc")
        if dvc_config is not None and dvc_config.get("auto_init", True):
            from .provenance import init_dvc, DvcNotInstalledError
            try:
                init_dvc(project_dir, dvc_config)
                created["dvc"] = True
                print("  + DVC initialized with local remote")
            except DvcNotInstalledError:
                created["dvc"] = False
                print(
                    "\n  WARNING: [dvc] section found in wf-canvas.toml but DVC is not installed.\n"
                    "  Install DVC with: pip install dvc\n"
                    "  Then re-run `wfc init` to configure DVC provenance."
                )
            except Exception as exc:
                created["dvc"] = False
                print(f"\n  WARNING: DVC setup failed: {exc}")
        else:
            created["dvc"] = False
    except FileNotFoundError:
        created["dvc"] = False

    口 = Step(step_num=7, name="Run-readiness health summary",
             purpose="Pre-flight git/DVC/Docker (Docker is a hard run-requirement "
                     "init can detect but not install) and print the closing health "
                     "table + honest archive note; init exits 0 regardless (D-4)")

    # Pre-flight all three run-requirements through the shared engine so the
    # summary matches `wfc doctor` exactly. None of these abort init.
    from .preflight import run_all_checks, render_health_table
    results = run_all_checks(project_dir)
    print()
    print(render_health_table(results))
    print(
        "\n  Note: your DVC archive holds run outputs indexed by .wfc/wfc.db.\n"
        "  The archive is NOT tracked in git — back up .wfc/ to keep provenance\n"
        "  recoverable."
    )

    return created


@task(purpose="Read the project wf-canvas.toml and return the database URL, project name, and pixi root")
def read_config(project_dir: Path) -> dict:
    """Read the project wf-canvas.toml and return parsed settings.

    Args:
        project_dir: Root directory of the wfc project.

    Returns:
        Dict with ``database_url``, ``project_name``, and ``pixi_root``.
        The ``pixi_root`` is a resolved absolute path string to the pixi
        environment root directory.

    Raises:
        FileNotFoundError: If wf-canvas.toml does not exist.
    """
    import tomllib

    口 = Step(step_num=1, name="Locate config file",
             purpose="Find .wfc/wf-canvas.toml in the project directory")

    project_dir = Path(project_dir).resolve()
    config_path = project_dir / ".wfc" / "wf-canvas.toml"
    if not config_path.exists():
        raise FileNotFoundError(
            f"No wfc project found at {project_dir} — run `wfc init` first"
        )

    口 = Step(step_num=2, name="Parse config",
             purpose="Read wf-canvas.toml with tomllib and extract settings")

    with open(config_path, "rb") as f:
        parsed = tomllib.load(f)

    result = {
        "database_url": parsed.get("database", {}).get("url"),
        "project_name": parsed.get("project", {}).get("name"),
    }

    口 = Step(step_num=3, name="Resolve pixi root",
             purpose="Parse [pixi] section and resolve the root path")

    pixi_section = parsed.get("pixi", {})
    pixi_root_raw = pixi_section.get("root", ".pixi")
    pixi_root_path = Path(pixi_root_raw)
    if not pixi_root_path.is_absolute():
        pixi_root_path = project_dir / pixi_root_path
    result["pixi_root"] = str(pixi_root_path.resolve())

    口 = Step(step_num=4, name="Parse conda config",
             purpose="Extract optional [conda] root for conda env resolution")

    conda_section = parsed.get("conda", {})
    conda_root_raw = conda_section.get("root", "")
    if conda_root_raw:
        conda_root_path = Path(conda_root_raw)
        if not conda_root_path.is_absolute():
            conda_root_path = project_dir / conda_root_path
        result["conda_root"] = str(conda_root_path.resolve())
    else:
        result["conda_root"] = ""

    口 = Step(step_num=5, name="Parse DVC config",
             purpose="Extract [dvc] section for provenance storage (ADR-007)")

    dvc_section = parsed.get("dvc", None)
    if dvc_section is not None:
        # ADR-018: prefer `url` (any scheme); fall back to legacy
        # `remote_path` (local-only) for backwards compatibility.
        result["dvc"] = {
            "url": dvc_section.get("url") or dvc_section.get("remote_path"),
            "remote_type": dvc_section.get("remote_type", "local"),
            "remote_path": dvc_section.get("remote_path"),
            "auto_init": dvc_section.get("auto_init", True),
        }
    else:
        result["dvc"] = None

    口 = Step(step_num=6, name="Parse registry config",
             purpose="Extract optional [registry] section for container image "
                     "publishing (ADR-019)")

    # ADR-019: [registry] block declares where built container images are
    # pushed. Absence is fine — projects that never build containers do not
    # need a registry. Cycle B owns the `wfc init` prompt that writes this
    # block; cycle A only reads it.
    registry_section = parsed.get("registry", None)
    if registry_section is not None:
        result["registry"] = {
            "url": registry_section.get("url"),
        }
    else:
        result["registry"] = None

    return result
