"""
Project initializer — scaffold a new wfc project directory.

Creates the `.wfc/` config directory, `modules/` and `methods/` directories,
`.runs/` artifact store, `.gitignore`, and initializes the SQLite database
with the full schema.

Usage:
    from wfc.init import init_project

    init_project(Path("."))          # scaffold current directory
    init_project(Path("my_project"))  # scaffold a specific directory
"""

from __future__ import annotations

import subprocess
import textwrap
from pathlib import Path
from . import layout
from .execution.pipeline import ENGINE_STATE_DIR_NAME

from axiom_annotations import workflow, Step

# Default config template (TOML). It holds only keys wfc reads: the [dvc]
# section. `[pixi] root` and `[conda] root` are optional overrides a user may
# add by hand; the config reader still honours them.
_DEFAULT_CONFIG = textwrap.dedent("""    # wfc project configuration
    # Generated by `wfc init`

""") + textwrap.dedent("""    # DVC provenance storage.
    # `url` is the artifact archive location (any DVC-supported scheme).
    # The default is a durable per-project directory outside this repo;
    # blobs there are indexed by `{db_relpath}`, so back up `{state_dir}/` to keep
    # provenance recoverable (the archive itself is not tracked in git).
    [dvc]
    url = "{dvc_url}"
    auto_init = true
""")

# The [dvc] section alone, appended to an existing config that lacks one.
_DVC_SECTION = textwrap.dedent("""
    # DVC provenance storage (added by `wfc init`).
    [dvc]
    url = "{dvc_url}"
    auto_init = true
""")

# Lines to add to .gitignore (only if not already present). Every path wfc
# creates is either committed or listed here.
_GITIGNORE_LINES = [
    layout.db_relpath(),
    f"{layout.STATE_DIR_NAME}/cache/",
    f"{layout.STATE_DIR_NAME}/{layout.BUILD_DIR_NAME}/",
    f"{layout.ARTIFACT_STORE_NAME}/",
    f"{layout.DATA_DIR_NAME}/",
    f"{layout.DVC_DIR_NAME}/cache/",
    f"{ENGINE_STATE_DIR_NAME}/",
    "__pycache__/",
]


class InitConfirmationRequired(RuntimeError):
    """Raised when ``init`` would change an existing project and cannot ask.

    Nothing has been changed when this is raised. Pass ``--yes``
    (``assume_yes=True``) to apply the listed changes without a prompt.
    """


def _is_git_repo(directory: Path) -> bool:
    """Return True if *directory* is inside a git working tree."""
    result = subprocess.run(
        ["git", "rev-parse", "--is-inside-work-tree"],
        cwd=str(directory),
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def _initial_commit(project_dir: Path, files: list[str]) -> str | None:
    """Commit exactly the files init wrote, by pathspec.

    Never the database file (it is ignored), and never anything else the user
    had staged. Uses an inline git identity so no global git config is
    required.

    Args:
        project_dir: The project root.
        files: Project-relative paths init wrote or changed.

    Returns:
        The new commit's SHA, or ``None`` when there was nothing to commit.
    """
    from .version import commit_paths
    return commit_paths(project_dir, files, "wfc init")


def _has_head_commit(directory: Path) -> bool:
    """Return True if the repo at *directory* has at least one commit (HEAD)."""
    result = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=str(directory), capture_output=True, text=True,
    )
    return result.returncode == 0


def _has_global_git_identity() -> bool:
    """Return True if both global user.name and user.email are configured."""
    name = subprocess.run(
        ["git", "config", "--global", "user.name"],
        capture_output=True, text=True,
    )
    email = subprocess.run(
        ["git", "config", "--global", "user.email"],
        capture_output=True, text=True,
    )
    return bool(name.stdout.strip()) and bool(email.stdout.strip())


# DVC-native remote schemes _normalize_archive recognizes, mapped to the
# plugin module each one needs at runtime.  Only ``dvc-http`` ships with
# the base ``dvc`` dependency — the rest require the matching ``dvc[<x>]``
# extra, so a scheme is only accepted when its plugin is importable.
# ``file`` is deliberately absent: local archives are stored as plain
# absolute paths (DVC accepts them directly), so a typed ``file://`` is
# rejected with a pointer to just enter the directory path.
_REMOTE_SCHEME_PLUGINS = {
    "s3": "dvc_s3",
    "ssh": "dvc_ssh",
    "gs": "dvc_gs",
    "azure": "dvc_azure",
    "gdrive": "dvc_gdrive",
    "webdav": "dvc_webdav",
    "webdavs": "dvc_webdav",
    "http": "dvc_http",
    "https": "dvc_http",
    "oss": "dvc_oss",
    "hdfs": "dvc_hdfs",
}


def _default_archive_url(project_dir: Path) -> str:
    """Return the default DVC archive location for a project.

    The default is a durable per-project directory under the user's home —
    ``~/.wfc/archives/<project>`` — expressed as a plain absolute path
    with forward slashes (``C:/Users/...`` on Windows: backslashes are
    escape characters inside wf-canvas.toml's quoted strings).  DVC
    accepts plain paths for local remotes on every platform; a ``file://``
    URL is NOT emitted because DVC's config schema rejects the
    ``file://C:/...`` form that drive-letter paths would produce.

    Args:
        project_dir: The project root (its name is used as the archive
            subdirectory name).

    Returns:
        An absolute path string (forward slashes).
    """
    return layout.default_archive_url(Path.home(), project_dir)


def _resolve_archive_url(
    project_dir: Path,
    archive: str | None = None,
    assume_yes: bool = False,
) -> str:
    """Resolve the DVC archive location for a fresh ``wfc init``.

    Resolution order:
      1. An explicit ``archive`` value (from ``--archive PATH``) — normalized
         (a bare path resolves to an absolute plain path).
      2. Otherwise, in non-interactive mode (``assume_yes``) or when stdin is
         not a TTY, the default.
      3. Otherwise, an interactive prompt that leads with what the archive is
         and lets the user press Enter to accept the default.  A rejected
         value (``file://`` / unknown scheme) re-prompts with the reason.

    Args:
        project_dir: The project root.
        archive: Explicit archive location, or ``None`` to use the default /
            prompt.
        assume_yes: When ``True``, skip the prompt and use the default.

    Returns:
        A plain absolute path or a scheme-qualified DVC remote URL.

    Raises:
        ValueError: When an explicit ``archive`` value is rejected by
            :func:`_normalize_archive` (interactive input re-prompts instead).
    """
    default = _default_archive_url(project_dir)

    if archive:
        return _normalize_archive(archive, project_dir)

    if assume_yes or not _stdin_is_interactive():
        return default

    print(
        "\nDVC archive (provenance storage)\n"
        "  wfc stores every run's outputs here, content-addressed and indexed\n"
        "  by .wfc/wfc.db. The default is a durable folder outside this repo.\n"
    )
    while True:
        try:
            answer = input(f"  Archive location [{default}]: ").strip()
        except EOFError:
            answer = ""
        if not answer:
            return default
        try:
            return _normalize_archive(answer, project_dir)
        except ValueError as exc:
            print(f"  {exc}")


def _normalize_archive(value: str, project_dir: Path) -> str:
    """Normalize a user-supplied archive location to what DVC accepts.

    A bare filesystem path (the common case) is expanded (``~``), resolved
    to an absolute path — relative paths resolve against *project_dir* —
    and returned as a plain path string.  A value carrying a DVC-native
    remote scheme (``s3://``, ``ssh://``, ...) is returned unchanged.
    ``file://`` and unrecognized schemes are rejected up front so a bad
    location fails at init with a clear message instead of at first push.

    Args:
        value: The user-supplied archive location.
        project_dir: The project root (for resolving relative paths).

    Returns:
        A plain absolute path or a scheme-qualified DVC remote URL.

    Raises:
        ValueError: On a ``file://`` value or an unsupported scheme.
    """
    value = value.strip()
    if "://" in value:
        scheme = value.split("://", 1)[0].lower()
        if scheme == "file":
            raise ValueError(
                f"archive location {value!r}: enter the directory path "
                "directly (no file:// prefix), e.g. "
                f"{_default_archive_url(project_dir)}"
            )
        plugin = _REMOTE_SCHEME_PLUGINS.get(scheme)
        if plugin is None:
            supported = ", ".join(
                f"{s}://" for s in sorted(_REMOTE_SCHEME_PLUGINS)
            )
            raise ValueError(
                f"archive location {value!r}: unsupported scheme "
                f"{scheme}:// — use a plain directory path or one of: "
                f"{supported}"
            )
        import importlib.util
        if importlib.util.find_spec(plugin) is None:
            extra = plugin.removeprefix("dvc_")
            raise ValueError(
                f"archive location {value!r}: {scheme}:// requires DVC's "
                f"{extra} plugin, which is not installed — install it with: "
                f"pip install 'dvc[{extra}]'"
            )
        return value
    path = Path(value).expanduser()
    if not path.is_absolute():
        path = (project_dir / path).resolve()
    else:
        path = path.resolve()
    # Forward slashes: the value is interpolated into wf-canvas.toml's
    # quoted strings, where backslashes are escape characters.
    return path.as_posix()


def _stdin_is_interactive() -> bool:
    """Return True if stdin is an interactive TTY (safe to prompt)."""
    import sys
    try:
        return sys.stdin is not None and sys.stdin.isatty()
    except (ValueError, AttributeError):
        return False


class _InitPlan:
    """What ``init`` would change in a project, listed before it changes it.

    Attributes:
        config_text: Text to write (fresh config) or append (existing config),
            or ``""`` when the config needs nothing.
        config_sections: ``(section, {key: value})`` pairs the config text
            adds, for the listing.
        new_config: True when the config file does not exist yet.
        ignore_lines: ``.gitignore`` lines to append.
        dvc_setup: True when DVC is to be set up.
        dvc_config: The ``[dvc]`` settings DVC is set up from.
    """

    def __init__(self) -> None:
        self.config_text = ""
        self.config_sections: list[tuple[str, dict[str, str]]] = []
        self.new_config = False
        self.ignore_lines: list[str] = []
        self.dvc_setup = False
        self.dvc_config: dict | None = None

    def is_empty(self) -> bool:
        """Return True when the project is already current."""
        return not (self.config_text or self.ignore_lines or self.dvc_setup)

    def files(self) -> list[str]:
        """Return the project-relative files applying this plan writes."""
        out: list[str] = []
        if self.ignore_lines:
            out.append(".gitignore")
        if self.config_text:
            out.append(layout.marker_relpath())
        if self.dvc_setup:
            out += [f"{layout.DVC_DIR_NAME}/config",
                    f"{layout.DVC_DIR_NAME}/.gitignore"]
        return out

    def render(self) -> str:
        """Return the three-group listing shown before confirmation."""
        lines = ["wfc init would make these changes:"]
        lines.append(f"  Config sections to add to {layout.marker_relpath()}:")
        if self.config_sections:
            for section, keys in self.config_sections:
                lines.append(f"    [{section}]")
                for k, v in keys.items():
                    lines.append(f"      {k} = {v}")
        else:
            lines.append("    (none)")
        lines.append("  Lines to append to .gitignore:")
        lines += [f"    {ln}" for ln in self.ignore_lines] or ["    (none)"]
        lines.append(
            f"  DVC: set up ({layout.DVC_DIR_NAME}/config, "
            f"{layout.DVC_DIR_NAME}/.gitignore)" if self.dvc_setup
            else "  DVC: already set up"
        )
        lines.append("  Files it would commit: " + ", ".join(self.files()))
        return "\n".join(lines)


def _plan_changes(
    project_dir: Path, archive: str | None, assume_yes: bool
) -> _InitPlan:
    """Work out what ``init`` has to add to bring *project_dir* current.

    Args:
        project_dir: The project root, resolved and existing.
        archive: An explicit, normalized ``--archive`` value, or ``None``.
        assume_yes: Whether prompting is disallowed (for the archive
            location).

    Returns:
        The plan. Empty when the project is already current.

    Raises:
        ValueError: When an explicit ``--archive`` differs from the ``[dvc]``
            url the existing config already holds; ``init`` does not rewrite
            a user's config key, and does not silently drop the value either.
    """
    plan = _InitPlan()
    config_path = layout.marker_path(project_dir)
    dvc_config: dict | None
    if not config_path.exists():
        dvc_url = _resolve_archive_url(
            project_dir, archive=archive, assume_yes=assume_yes
        )
        plan.new_config = True
        plan.config_text = _DEFAULT_CONFIG.format(
            dvc_url=dvc_url,
            db_relpath=layout.db_relpath(),
            state_dir=layout.STATE_DIR_NAME,
        )
        plan.config_sections.append(
            ("dvc", {"url": f'"{dvc_url}"', "auto_init": "true"})
        )
        dvc_config = {"url": dvc_url, "auto_init": True}
    else:
        import tomllib
        existing = tomllib.loads(config_path.read_text(encoding="utf-8"))
        dvc_config = existing.get("dvc")
        if dvc_config is None:
            dvc_url = _resolve_archive_url(
                project_dir, archive=archive, assume_yes=assume_yes
            )
            plan.config_text = _DVC_SECTION.format(dvc_url=dvc_url)
            plan.config_sections.append(
                ("dvc", {"url": f'"{dvc_url}"', "auto_init": "true"})
            )
            dvc_config = {"url": dvc_url, "auto_init": True}
        elif archive:
            current = dvc_config.get("url") or dvc_config.get("remote_path")
            if current != archive:
                raise ValueError(
                    f"--archive {archive!r} differs from the [dvc] url "
                    f"{current!r} already in {layout.marker_relpath()}; init "
                    "does not rewrite an existing config key. Edit the url "
                    "there, or drop --archive."
                )

    gitignore = project_dir / ".gitignore"
    existing_ignore = gitignore.read_text() if gitignore.exists() else ""
    present = {ln.strip() for ln in existing_ignore.splitlines()}
    plan.ignore_lines = [line for line in _GITIGNORE_LINES if line not in present]

    if dvc_config is not None and dvc_config.get("auto_init", True):
        dvc_dir = layout.dvc_dir(project_dir)
        if not ((dvc_dir / "config").exists()
                and (dvc_dir / ".gitignore").exists()):
            plan.dvc_setup = True
            plan.dvc_config = dvc_config
    return plan


def _confirm(plan: _InitPlan, assume_yes: bool) -> bool:
    """Show the plan and ask once whether to apply it.

    Args:
        plan: The non-empty plan.
        assume_yes: ``--yes``: apply without asking.

    Returns:
        True to apply, False to change nothing.

    Raises:
        InitConfirmationRequired: With no TTY and no ``--yes``.
    """
    print(plan.render())
    if assume_yes:
        return True
    if not _stdin_is_interactive():
        raise InitConfirmationRequired(
            "wfc init: this is an existing project and init cannot ask for "
            "confirmation without a terminal. Nothing was changed. Re-run "
            "with --yes to apply the changes listed above."
        )
    try:
        answer = input("Apply these changes? [y/N]: ").strip().lower()
    except EOFError:
        answer = ""
    return answer in ("y", "yes")


@workflow(purpose="Scaffold a new wfc project directory with database, config, and artifact store")
def init_project(
    project_dir: Path,
    init_git: bool = False,
    archive: str | None = None,
    assume_yes: bool = False,
) -> dict[str, bool]:
    """Scaffold a wfc project directory and wire it up to be runnable.

    Creates the directory structure and config files needed for a new wfc
    project, then brings the project to a runnable state: a live DVC
    archive, a git repo whose tree is clean, and a Docker pre-flight check.

    In a fresh directory (no config, no git history) it applies everything
    without asking. In an existing project (a config already there, or a git
    repository with commits) it first lists what it would change -- config
    sections to add, ``.gitignore`` lines to append, whether DVC is set up,
    and the files it would commit -- and asks once. On no it changes
    nothing. ``assume_yes`` answers yes. With no terminal and no
    ``assume_yes`` it changes nothing and raises
    :class:`InitConfirmationRequired`. A project with nothing to add is
    already current: nothing is asked and nothing is committed.

    DVC is set up before the commit, and the commit names exactly the files
    init wrote (``.gitignore``, ``.wfc/wf-canvas.toml``, ``.dvc/config``,
    ``.dvc/.gitignore``), so nothing else the user staged is swept in and
    the tree is clean afterwards.

    git and Docker are hard run-requirements that init detects and surfaces
    but never installs. A missing or failing git or Docker does NOT abort
    init: the files are still written, the gap is shown in the closing
    health summary, and init still returns.

    Args:
        project_dir: Root directory for the project (created if needed).
        init_git: Accepted and ignored -- git is always initialized. Kept
            for backward compatibility with scripts/docs.
        archive: Explicit DVC archive location (a directory path or a
            DVC remote URL such as ``s3://...``). When provided, the
            wizard does not prompt for it. Defaults to
            ``~/.wfc/archives/<project>``.
        assume_yes: When ``True``, run fully non-interactively (accept all
            defaults and apply the listed changes, never call ``input()``).
            Set by ``wfc init --yes``.

    Returns:
        Dict mapping each created resource name to ``True`` if created
        or ``False`` if already existed. Empty when the user declined.

    Raises:
        ValueError: On a rejected ``--archive`` value, or one that differs
            from an existing config's ``[dvc]`` url.
        InitConfirmationRequired: An existing project needs changes and
            there is no terminal to confirm them and no ``assume_yes``.
    """
    project_dir = Path(project_dir).resolve()
    # Validate an explicit --archive value up front (ValueError on file://,
    # unknown scheme, or missing DVC plugin) so a bad location refuses
    # before any scaffolding.
    if archive:
        archive = _normalize_archive(archive, project_dir)

    created: dict[str, bool] = {}

    口 = Step(step_num=1, name="Plan and confirm",
             purpose="List what init would add (config sections, ignore lines, "
                     "DVC setup, files to commit); in an existing project ask "
                     "once and change nothing on no")
    existing = project_dir.exists() and (
        layout.marker_path(project_dir).exists()
        or (_is_git_repo(project_dir) and _has_head_commit(project_dir))
    )
    project_dir.mkdir(parents=True, exist_ok=True)
    plan = _plan_changes(project_dir, archive, assume_yes)
    if existing:
        if plan.is_empty():
            print("wfc init: the project is already current; nothing to change.")
        elif not _confirm(plan, assume_yes):
            print("wfc init: nothing was changed.")
            return {}

    口 = Step(step_num=2, name="Create project directories",
             purpose="Make .wfc/, modules/, methods/, data/samples/ and .runs/ "
                     "without overwriting existing content")
    for key, path in (
        (f"{layout.STATE_DIR_NAME}/", layout.state_dir(project_dir)),
        (f"{layout.MODULES_DIR_NAME}/", layout.modules_dir(project_dir)),
        (f"{layout.METHODS_DIR_NAME}/", layout.methods_dir(project_dir)),
        (f"{layout.DATA_DIR_NAME}/{layout.SAMPLES_DIR_NAME}/",
         layout.samples_dir(project_dir)),
        (f"{layout.ARTIFACT_STORE_NAME}/", layout.artifact_store(project_dir)),
    ):
        created[key] = not path.exists()
        path.mkdir(parents=True, exist_ok=True)

    口 = Step(step_num=3, name="Write config file",
             purpose="Write wf-canvas.toml (only [dvc]) when missing, or append "
                     "the [dvc] section an existing config lacks")
    config_path = layout.marker_path(project_dir)
    if plan.new_config:
        config_path.write_text(plan.config_text, encoding="utf-8")
    elif plan.config_text:
        with open(config_path, "a", encoding="utf-8") as fh:
            fh.write(plan.config_text)
    created["wf-canvas.toml"] = bool(plan.new_config)

    口 = Step(step_num=4, name="Initialize database",
             purpose="Create the SQLite database with the full schema through "
                     "Persistence's engine bootstrap, leaving the process "
                     "engine and the environment untouched")
    db_path = layout.db_path(project_dir)
    created["wfc.db"] = not db_path.exists()
    from .persistence import bootstrap_engine
    bootstrap_engine(layout.database_url(project_dir)).dispose()

    口 = Step(step_num=5, name="Update .gitignore",
             purpose="Append wfc-specific ignore rules without overwriting "
                     "existing entries")
    gitignore_path = project_dir / ".gitignore"
    existing_ignore = gitignore_path.read_text() if gitignore_path.exists() else ""
    if plan.ignore_lines:
        separator = "\n" if existing_ignore and not existing_ignore.endswith("\n") else ""
        gitignore_path.write_text(
            existing_ignore + separator + "\n".join(plan.ignore_lines) + "\n"
        )
    created[".gitignore"] = bool(plan.ignore_lines)

    口 = Step(step_num=6, name="Initialize DVC provenance",
             purpose="Set DVC up from the [dvc] section before the commit; "
                     "init_dvc writes the DVC dir's .gitignore, which keeps the "
                     "cache and credentials out of git")
    created["dvc"] = False
    if plan.dvc_setup and plan.dvc_config is not None:
        from .storage import init_dvc, DvcNotInstalledError
        try:
            init_dvc(project_dir, plan.dvc_config)
            created["dvc"] = True
            archive_loc = plan.dvc_config.get("url") or plan.dvc_config.get("remote_path")
            print(f"  + DVC initialized (archive: {archive_loc})")
        except DvcNotInstalledError:
            print(
                "\n  WARNING: [dvc] section found in wf-canvas.toml but DVC is not installed.\n"
                "  Install DVC with: pip install dvc\n"
                "  Then re-run `wfc init` to configure DVC provenance."
            )
        except Exception as exc:  # noqa: BLE001 — continue-on-fail by design
            print(f"\n  WARNING: DVC setup failed: {exc}")

    口 = Step(step_num=7, name="Initialize git repository and commit",
             purpose="git is a hard run-requirement: git init when needed, then "
                     "commit exactly the files init wrote, by pathspec; "
                     "continue-on-fail (never abort init)")
    created[".git/"] = False
    try:
        if not _is_git_repo(project_dir):
            init_res = subprocess.run(
                ["git", "init", str(project_dir)],
                capture_output=True, text=True,
            )
            if init_res.returncode != 0:
                raise RuntimeError(init_res.stderr.strip() or "git init failed")
            created[".git/"] = True
            print("  + Initialized git repository.")
        sha = _initial_commit(project_dir, plan.files())
        if sha is not None:
            print(f"  + Committed {', '.join(plan.files())} ({sha[:12]}).")
            if not _has_global_git_identity():
                print(
                    "    (committed with a fallback identity 'wfc <wfc@wfc>';\n"
                    "     set your own with `git config user.name/user.email`)"
                )
    except FileNotFoundError:
        print("\n  WARNING: git is not installed — see the health summary below.")
    except Exception as exc:  # noqa: BLE001 — continue-on-fail by design
        print(f"\n  WARNING: git setup did not complete: {exc}")

    口 = Step(step_num=8, name="Run-readiness health summary",
             purpose="Pre-flight git/DVC/Docker/samples (Docker is a hard "
                     "run-requirement init can detect but not install; the "
                     "samples probe reports the new project's empty registry) "
                     "and print the closing health table + honest archive "
                     "note; init returns regardless")
    from .execution.readiness import run_all_checks
    from .preflight import render_health_table
    results = run_all_checks(project_dir)
    print()
    print(render_health_table(results))
    print(
        "\n  Note: your DVC archive holds run outputs indexed by .wfc/wfc.db.\n"
        "  The archive is NOT tracked in git — back up .wfc/ to keep provenance\n"
        "  recoverable."
    )

    return created
